### ISSUE TITLE
应该用 python3 setup.py install  进行安装

### ISSUE THREAD

**Issue by luojiyin1987** [xianhu/PSpider#1]
我用的是Ubuntu16.04  ，装有python2.7.12 和 python3.5.2 。python 默认是指向python2.7.12。使用 python  setup.py install  安装的话，有各种奇怪问题。

**Comment by liuxs981001** [comment]
你可以用PyCharm这个IDE（Community版和Pro版对于一般用户差别不大），然后直接在这里面来装就可以了，相对来说方便一些







在2016年11月30日 16:47， luo jiyin<notifications@github.com>写道：

我用的是Ubuntu16.04 ，装有python2.7.12 和 python3.5.2 。python 默认是指向python2.7.12。使用 python setup.py install 安装的话，有各种奇怪问题。

**Comment by xianhu** [comment]
不支持python2.x版本哦
