### ISSUE TITLE
直接使用setup.py安装的时候发现bitarray安装不上

### ISSUE THREAD

**Issue by shop271** [xianhu/PSpider#14]
bitarray最新的.8只支持到python3.3，这个模块安装的时候一直报错

**Comment by xianhu** [comment]
Linux上应该可以装上

**Comment by shop271** [comment]
嗯，我前面安装是自己通过执行安装环境，linux上执行setup就可以安装上去了。使用setup安装的时候怎么避开这个版本问题的？
