### ISSUE TITLE
AttributeError: module 'spider' has no attribute 'YunDaMa

### ISSUE THREAD

**Issue by Z-Tracy** [xianhu/PSpider#16]
不太明白weibo_user.py 中的 WeiBoLogin `        self.cookie_jar, self.opener = None, None
        self.yundama = spider.YunDaMa("", "")` 这段，调用的时候也出错说‘AttributeError: module 'spider' has no attribute 'YunDaMa'’ 去spider里找了下也并没有找到有YunDaMa相关，不知道这里是什么用法还是缺失是一个bug了。

**Comment by xianhu** [comment]
这里把YunDaMa这个模块从spider中移除了。你可以自己封装一个类似的接口，或者直接进行人工打吗。
项目中的demos_*不保证一定能运行，因为spider模块一直在更新，我这边精力有限，没办法实时更新demos_*项目。

**Comment by Z-Tracy** [comment]
好的明白了
