### ISSUE TITLE
介绍可以再详细一些

### ISSUE THREAD

**Issue by baif666** [xianhu/PSpider#2]
感觉README里主要说的项目的构成，最好写个turtoial，别人看到也能更好上手

**Comment by xianhu** [comment]
有时间会补充完整的！

**Comment by baif666** [comment]
我倒是愿意帮忙，不过还没搞清楚是怎么回事

**Comment by xianhu** [comment]
非常欢迎！

**Comment by MonkeyRing** [comment]
使用流程，怎么使用的希望也可以介绍一下。

**Comment by baif666** [comment]
感觉可以先把优化放一放，把文档先写起来，要是大家连怎么用都不知道，就不可能贡献自己的力量了

**Comment by xianhu** [comment]
嗯。以前都是自己用。我会尽快写一个中文文档。

**Comment by baif666** [comment]
写好了文档大家才能做贡献，加油ヾ(^▽^*)))

**Comment by xianhu** [comment]
文档第一版已经写好了，大家可以看一下

**Comment by baif666** [comment]
感觉写的不错，基本看懂了，准备自己试试（之前看Scrapy的toturial，居然没看懂）。感谢楼主的工作。

**Comment by MrWanter** [comment]
请问文档在哪里呢？谢谢
