### ISSUE TITLE
请问框架中的priority， keys分别代表什么？

### ISSUE THREAD

**Issue by GEeKkk** [xianhu/PSpider#30]
而且`keys={"type": "360"}`似乎并没有起作用，（` web_spider.set_start_url("http://zhushou.360.cn/", priority=0, keys={"type": "360"}, deep=0)`）

**Comment by xianhu** [comment]
keys是一个跟着url的变量，目的是用于一些数据的传递。

举个例子，比如你想抓应用商店的所有应用的数据，那你需要分两步：
1、抓取列表，获取每个应用的详细url地址。
2、抓取每个应用的详细信息。

这时候可能会出现一个问题：应用的某个字段，比如packagename，只有在列表页中有，详情页中无法找到。此时就可以用到这个keys字段。即你在解析完列表页，返回详情页url的时候，对每个url附带一个keys变量，内容就是{"packagename": "xxx"}，这样你在后边抓取或者解析详情页的时候，就可以加上这个字段了。

这就是keys这个字段的应用场景，还是挺普遍的。

**Comment by zy15626299617** [comment]
你好，我是最近才开始接触python爬虫，一边看书一边google来爬豆瓣。
因为没系统学过python，所以我照着text.py去阅读的时候我还是不太能理解该如何使用这个框架，我觉得我应该是要定义我自己的fetcher,parser.saver 但是实在是不理解如何去重写他们。
我是在[https://juejin.im/entry/583fdf2c128fe1005762e66c](url)看到你的文章，我开启50个线程去爬取电影页面，设置了足够充足的停顿时间，并且有用session.cookies进行模拟登录，并周期性更新我的cookies，但我依旧在爬1000多条的时候被封了IP，我尝试过用tor洋葱路由来伪装IP，虽然可行，但是需要经过加密通道得到返回结果，这个过程实在过于缓慢，我不得不放弃，而selenium的效率也一样慢。
所以我觉得遇到了一个瓶颈，请问你可以给我一点建议吗，非常感谢。
