### ISSUE TITLE
抓取豆瓣电影bid随机策略

### ISSUE THREAD

**Issue by Resemble** [xianhu/PSpider#6]
请问一下，那个bid随机的策略还能用吗，之前我用了一下还能用，今天不能用了，你那边怎么样呢

**Comment by qijianjun** [comment]
我抓API试了下是不行的，不过API的限制策略比较明确，每小时500请求，似乎是不考虑cookie的

**Comment by xuzhenyang** [comment]
不能用了+1

**Comment by xianhu** [comment]
我刚试了，能用。这里要说明一点，如果你现在已经处于被封的状态，这个策略是没有办法的。随机bid能保证你不会被封，但是不能让你从被封的状态转化为不被封。

**Comment by liusiye** [comment]
似乎现在这个策略已经不行了~

**Comment by xianhu** [comment]
你试试直接访问可以吗？参考我上一个评论：

> 这里要说明一点，如果你现在已经处于被封的状态，这个策略是没有办法的。随机bid能保证你不会被封，但是不能让你从被封的状态转化为不被封。

**Comment by liusiye** [comment]
检测到有异常请求从你的 IP 发出，请 <a href="https://www.douban.com/accounts/login?redir=https%3A%2F%2Fbook.douban.com%2Fsubject%2F11801459%2F">登录</a> 使用豆瓣。

爬了大概一个小时后，会要求登录~~~~

**Comment by xianhu** [comment]
我还没抓过那么久。这就需要你再去试验更好的策略了，或者更换IP地址
