### ISSUE TITLE
如何用redis取代PriorityQueue

### ISSUE THREAD

**Issue by sbitpdc** [xianhu/PSpider#8]
当我使用 redis 取代 PriorityQueue 时，无法结束线程。

**Comment by xianhu** [comment]
是的。在我的框架里，线程结束是有条件的。建议你仔细读一下源码，参考文件：
https://github.com/xianhu/PSpider/blob/master/spider/abcbase/abc_base.py
https://github.com/xianhu/PSpider/blob/master/spider/concurrent/concur_threads.py
参考关键字：BasePool.number_dict, BasePool. is_all_tasks_done()

**Comment by sbitpdc** [comment]
我修改了方法
`    async def _start(self, fetcher_num):
        """
        start this pool, and wait for finishing
        """
        tasks_list = [asyncio.Task(self.work(index), loop=self.loop) for index in range(fetcher_num)]
        # await self.queue.join()
        await asyncio.sleep(1)
        for task in tasks_list:
            task.cancel()
        self.print_status()
        return
    def finish_a_task(self, task_name):
        """
        finish a task based on task_name, call queue.task_done()
        """

        # self.queue.task_done()
        self.update_number_dict(TPEnum.TASKS_RUNNING, -1)
        return
`
这个时候如何结束？我把 queue 的 get, put 都替换成了 redis 的 list 操作。

**Comment by sbitpdc** [comment]
BaseThread 怎么被调用的？

**Comment by sbitpdc** [comment]
我看了你的源码，除了BaseThread使用了 is_all_tasks_done 外，其他地方都没有调用 is_all_tasks_done。而 BaseThread 的 run 方法也没被调用。我使用的 WebSpiderAsync 。

**Comment by xianhu** [comment]
异步中是不需要is_all_tasks_done这个判断的。异步中是没有线程概念的，只有协程的概念。建议你先了解下Python中的协程用法和机制。WebSpiderAsync的finish_a_task函数中调用了queue.task_done()，当去全部任务结束时，queue.join()结束，整个程序也就结束了。

**Comment by sbitpdc** [comment]
哦，是我开始问的时候没说明白我是用异步时候遇到的问题。我现在使用的是异步，把你源码里的 queue 全部都改为了 redis

**Comment by xianhu** [comment]
异步停止使用的queue.join()，并没有用到self.number_dict。

**Comment by sbitpdc** [comment]
我知道，现在代码里面都没有 queue 了

**Comment by xianhu** [comment]
嗯，能说一下你用Redis的目的吗？

**Comment by sbitpdc** [comment]
用作分布式爬数据。不过我可以换下策略。

**Comment by xianhu** [comment]
嗯，可以发一下你的代码吗？

**Comment by sbitpdc** [comment]
可以。在 finish_a_task 方法里面，把 self.queue.task_done() 注释掉，‘



`

    import sys
    import datetime
    import logging
    import simplejson as json
    import asyncio
    import aiohttp
    from spider import WebSpiderAsync
    from spider.concurrent.abc_base import TPEnum
    from spider.utilities import make_random_useragent
    from redis import Redis

    class BaseRedisSpider(WebSpiderAsync):
    """
    使用 redis 作为队列
    """
    def __init__(self, max_repeat=3, sleep_time=0, max_deep=0, save_pipe=sys.stdout, url_filter=None, loop=None,
                 redis_opt=None):
        """
        constructor
        """
        if redis_opt is None:
            self.redis = Redis()
        else:
            self.redis = Redis(host=redis_opt['host'], port=redis_opt['port'],
                               password=redis_opt['password'], db=redis_opt['db'])
        self.max_repeat = max_repeat        # default: 3, maximum repeat fetching time for a url
        self.sleep_time = sleep_time        # default: 0, sleeping time after a fetching for a url
        self.max_deep = max_deep            # default: 0, if -1, spider will not stop until all urls are fetched
        self.save_pip = save_pipe           # default: sys.stdout, also can be a file handler
        self.loop = loop or asyncio.get_event_loop()            # event_loop from parameter or call get_event_loop()
        self.url_filter = url_filter        # default: None, also can be UrlFilter()
        self.number_dict = {
            TPEnum.TASKS_RUNNING: 0,        # the count of tasks which are running
            TPEnum.URL_FETCH: 0,            # the count of urls which have been fetched successfully
            TPEnum.HTM_PARSE: 0,            # the count of urls which have been parsed successfully
            TPEnum.ITEM_SAVE: 0,            # the count of urls which have been saved successfully
            TPEnum.URL_NOT_FETCH: 0,        # the count of urls which haven't been fetched
            TPEnum.HTM_NOT_PARSE: 0,        # the count of urls which haven't been parsed
            TPEnum.ITEM_NOT_SAVE: 0,        # the count of urls which haven't been saved
        }
        return

    def start_work_and_wait_done(self, fetcher_num=10, is_over=True):
        """
        start this pool, and wait for finishing
        :param fetcher_num: the count of tasks
        :param is_over: not useful in this class
        """
        try:
            self.loop.run_until_complete(self._start(fetcher_num=fetcher_num))
        except KeyboardInterrupt as excep:
            logging.warning("%s KeyboardInterrupt: %s", self.__class__.__name__, excep)
        finally:
            self.loop.stop()
            self.loop.run_forever()
            self.loop.close()
        return

    async def _start(self, fetcher_num):
        """
        start this pool, and wait for finishing
        """
        tasks_list = [asyncio.Task(self.work(index), loop=self.loop) for index in range(fetcher_num)]
        # await self.queue.join()
        await asyncio.sleep(1)
        for task in tasks_list:
            task.cancel()
        self.print_status()
        return

    async def work(self, index):
        """
        working process, fetching --> parsing --> saving
        """
        logging.warning("Worker[%s] start", index)
        headers = {"User-Agent": make_random_useragent(), "Accept-Encoding": "gzip"}
        session = aiohttp.ClientSession(loop=self.loop, headers=headers)
        try:
            while True:
                task_content = await self.get_a_task(task_name=TPEnum.URL_FETCH)
                if task_content is not None:
                    priority, url, keys, deep, repeat = task_content
                    # fetch the content of a url ================================================================
                    fetch_result, content = await self.fetch(session, url, keys, repeat)
                    if fetch_result > 0:
                        self.update_number_dict(TPEnum.URL_FETCH, +1)
                        # parse the content of a url ============================================================
                        self.update_number_dict(TPEnum.HTM_NOT_PARSE, +1)
                        parse_result, url_list, save_list = await self.parse(priority, url, keys, deep, content)
                        self.update_number_dict(TPEnum.HTM_NOT_PARSE, -1)

                        if parse_result > 0:
                            self.update_number_dict(TPEnum.HTM_PARSE, +1)

                            # add new task to self.queue
                            for _url, _keys, _priority in url_list:
                                self.add_a_task(TPEnum.URL_FETCH, (_priority, _url, _keys, deep+1, 0))

                            # save the item of a url ============================================================
                            for item in save_list:
                                self.update_number_dict(TPEnum.ITEM_NOT_SAVE, +1)
                                save_result = await self.save(url, keys, item)
                                self.update_number_dict(TPEnum.ITEM_NOT_SAVE, -1)

                                if save_result:
                                    self.update_number_dict(TPEnum.ITEM_SAVE, +1)

                    elif fetch_result == 0:
                        self.add_a_task(TPEnum.URL_FETCH, (priority+1, url, keys, deep, repeat+1))
                    else:
                        pass

                self.finish_a_task(task_name=TPEnum.URL_FETCH)
                # print the information of this pool
                if self.number_dict[TPEnum.URL_FETCH] % 100 == 0:
                    self.print_status()
        except asyncio.CancelledError:
            logging.warning("Worker[%s] end", index)

        session.close()
        return

    def finish_a_task(self, task_name):
        """
        finish a task based on task_name, call queue.task_done()
        """

        self.queue.task_done()
        self.update_number_dict(TPEnum.TASKS_RUNNING, -1)
        return

    async def get_a_task(self, task_name):
        """
        get a task based on task_name, if redis list is empty, raise queue empty error
        :param task_name: redis list key name
        :return
        """
        task_content = self.redis.rpop(task_name)
        if task_content:
            task_content = json.loads(task_content)
        else:
            return None
        self.update_number_dict(TPEnum.URL_NOT_FETCH, -1)
        self.update_number_dict(TPEnum.TASKS_RUNNING, +1)
        return task_content

    def add_a_task(self, task_name, task_content):
        """
        add a task based on task_name, if queue is full, blocking the queue
        :param task_name: redis list key name
        :param task_content: 工作内容
        """
        if (task_content[-1] > 0) or (not self.url_filter) or self.url_filter.check_and_add(task_content[1]):
            self.redis.lpush(task_name, json.dumps(task_content))
            self.update_number_dict(TPEnum.URL_NOT_FETCH, +1)
        return
`

**Comment by sbitpdc** [comment]
这是我拿来调试用的代码，有些你可以删掉

**Comment by xianhu** [comment]
可以将await self.queue.join() 改为：
 while self.number_dict[TPEnum.URL_NOT_FETCH] or self.number_dict[TPEnum.TASKS_RUNNING]:
            await asyncio.sleep(1)

**Comment by sbitpdc** [comment]
修改几处代码已经可以用了, Thanks!

**Comment by xianhu** [comment]
嗯，不客气
